-- SAFE DIV 

-- RETURN a / b or if b == 0 0
DELIMITER $$
CREATE FUNCTION SafeDiv(a INT,b INT)
RETURNS FLOAT DETERMINISTIC
BEGIN
  IF b = 0 or ISNULL(b) or ISNULL(a)
    THEN
    RETURN 0;
  END IF
  RETURN a DIV b;
END$$
